-- V1__init.sql
-- Table des Utilisateurs
CREATE TABLE crm_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table des Prospects
CREATE TABLE prospect (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    activity_sector VARCHAR(50) NOT NULL,
    city VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    website VARCHAR(255),
    source VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'nouveau' NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_interaction_at TIMESTAMP WITH TIME ZONE,
    owner_id BIGINT NOT NULL,
    CONSTRAINT fk_prospect_owner FOREIGN KEY (owner_id) REFERENCES crm_user(id) ON DELETE CASCADE
);

-- Table des Contacts
CREATE TABLE contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    job_title VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    linkedin_url VARCHAR(255),
    notes TEXT,
    CONSTRAINT fk_contact_prospect FOREIGN KEY (prospect_id) REFERENCES prospect(id) ON DELETE CASCADE
);

-- Table des Interactions
CREATE TABLE interaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id BIGINT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    type VARCHAR(50) NOT NULL,
    notes TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_interaction_prospect FOREIGN KEY (prospect_id) REFERENCES prospect(id) ON DELETE CASCADE
);
