-- V2__seed_data.sql
-- Insertion des Utilisateurs (Mot de passe: Pyramidev2026!)
INSERT INTO crm_user (id, email, password_hash, full_name) VALUES
(1, 'admin@pyramidev.com', '$2b$10$R9U0ACFa91Sl4TKZVO5Mp.jiGo/HO0ZB0IaR05HFYxL0Sb/UlHiPK', 'Admin Pyramidev'),
(2, 'com1@pyramidev.com', '$2b$10$R9U0ACFa91Sl4TKZVO5Mp.jiGo/HO0ZB0IaR05HFYxL0Sb/UlHiPK', 'Commercial 1');

-- Réajuster les séquences H2/PostgreSQL
-- H2 supporte GENERATED BY DEFAULT AS IDENTITY, et ceci est géré automatiquement, mais nous fixons les IDs explicites d'abord.

-- Insertion des Prospects
INSERT INTO prospect (id, name, activity_sector, city, phone, website, source, status, notes, owner_id, last_interaction_at) VALUES
(1, 'DistriFood SARL', 'grossiste', 'Casablanca', '+212522001122', 'https://distrifood.ma', 'recommandation', 'nouveau', 'Entreprise intéressée pour équiper ses commerciaux de terrain avec DistriMob.', 1, NULL),
(2, 'CosmeBelle', 'cosmétique', 'Marrakech', '+212524334455', 'https://cosmebelle.ma', 'LinkedIn', 'RDV planifié', 'PME en forte croissance. Cherche à digitaliser sa prise de commande.', 1, '2026-07-05 15:30:00+00'),
(3, 'PharmaNord', 'pharma', 'Tanger', '+212539887766', 'https://pharmanord.ma', 'salon', 'démo réalisée', 'Laboratoire pharmaceutique régional. Besoin d''intégrer les commandes terrain avec leur ERP.', 2, '2026-06-25 14:00:00+00');

-- Insertion des Contacts
INSERT INTO contact (id, prospect_id, first_name, last_name, job_title, email, phone, linkedin_url, notes) VALUES
(1, 2, 'Amine', 'Radi', 'Directeur Général', 'amine@cosmebelle.ma', '+212661223344', 'https://linkedin.com/in/amineradi', 'Décideur final. Très pragmatique.'),
(2, 3, 'Sara', 'Lahlou', 'Responsable IT', 's.lahlou@pharmanord.ma', '+212661556677', NULL, 'Interlocutrice technique principale.');

-- Insertion des Interactions
INSERT INTO interaction (id, prospect_id, date, type, notes) VALUES
(1, 2, '2026-07-01 10:00:00+00', 'LinkedIn', 'Premier contact établi sur LinkedIn. Amine montre un vif intérêt.'),
(2, 2, '2026-07-05 15:30:00+00', 'RDV', 'Réunion de démonstration en visio. Très bien passée. Proposition commerciale envoyée.'),
(3, 3, '2026-06-15 11:00:00+00', 'appel', 'Appel de qualification. Validation du besoin de synchronisation ERP.'),
(4, 3, '2026-06-25 14:00:00+00', 'démo', 'Présentation technique de l''API DistriMob à Sara. Elle valide l''architecture.');

-- Repositionner l'auto-incrémentation
-- Pour H2/PostgreSQL pour éviter les conflits d'ID lors de l'insertion de nouveaux éléments
ALTER TABLE crm_user ALTER COLUMN id RESTART WITH 3;
ALTER TABLE prospect ALTER COLUMN id RESTART WITH 4;
ALTER TABLE contact ALTER COLUMN id RESTART WITH 3;
ALTER TABLE interaction ALTER COLUMN id RESTART WITH 5;
